from django.conf.urls.defaults import *

# place app url patterns here
urlpatterns = patterns('',
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/consol/$', 
        "commitlog.views.consol_view", name='commitlog-consol'),
	url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/edit/(?P<path>[a-zA-Z0-9\-_\.\/]+)$', 
		"commitlog.views.edit_file", name='commitlog-edit-file'),
	url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/new/(?P<path>[a-zA-Z0-9\-_\.\/]+)$', 
		"commitlog.views.new_file", name='commitlog-new-file'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/delete/(?P<path>[a-zA-Z0-9\-_\.\/\\]+)$', 
        "commitlog.views.delete_file", name='commitlog-delete-file'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/rename/(?P<file_path>[a-zA-Z0-9\-_\.\/\\]+)$', 
        "commitlog.views.rename_file", name='commitlog-rename-file'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/tree/(?P<path>[a-zA-Z0-9\-_\.\/]*)$', 
    	"commitlog.views.tree_view", name='commitlog-tree-view'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/(?P<commit_sha>[a-zA-Z0-9\-_\.\/]*)/tree/(?P<path>[a-zA-Z0-9\-_\.\/]*)$', 
        "commitlog.views.tree_view", name='commitlog-commit-tree-view'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/view/(?P<commit_sha>[a-zA-Z0-9\-_\.\/]*)$', 
        "commitlog.views.commit_view", name='commitlog-commit-view'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/(?P<commit_sha>[a-z0-9\-_]+)/view/(?P<path>[a-zA-Z0-9\-_\.\/]*)$', 
        "commitlog.views.view_file", name='commitlog-view-file'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/history/(?P<path>[a-zA-Z0-9\-_\.\/]*)$', 
        "commitlog.views.log_view", name='commitlog-history-file'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/diff/(?P<path>[a-zA-Z0-9\-_\.\/]*)$', 
        "commitlog.views.diff_view", name='commitlog-diff-file'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/$', 
    	"commitlog.views.log_view", name='commitlog-branch'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/undo/$', 
        "commitlog.views.undo_commit", name='commitlog-undo'),
    
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/(?P<branch>[a-z0-9\-_]+)/search/$', 
        "commitlog.views.search_view", name='commitlog-search'),
    url(r'^(?P<repo_name>[a-z0-9\-_]+)/$', 
    	"commitlog.views.branches_view", name='commitlog-branches'),
    
    url(r'^$', 
    	"commitlog.views.repos_view", name='commitlog-repos'),
)